### ISSUE TITLE
pass-authz integration tests failing due to github move

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#242]
Using Java 8, run the ITs with
```
mvn verify
```

The underlying errors are problems like:
```
java.lang.RuntimeException: A problem occurred while attempting to create a Resource: Failed to update null - unexpected status code 400: Could not parse jsonld: loading remote context failed: https://oa-pass.github.io/pass-data-model/src/main/resources/context-3.5.jsonld
        at org.dataconservancy.pass.authz.PassAuthzIT.userBasedPermissionIT(PassAuthzIT.java:96)
Caused by: java.lang.RuntimeException: Failed to update null - unexpected status code 400: Could not parse jsonld: loading remote context failed: https://oa-pass.github.io/pass-data-model/src/main/resources/context-3.5.jsonld
        at org.dataconservancy.pass.authz.PassAuthzIT.userBasedPermissionIT(PassAuthzIT.java:96)
```

This occurs because pass-java-client needs to be updated to the new JSON-LD context location.

**Comment by markpatton** [comment]
Fixed by making the context resolvable again.
