### ISSUE TITLE
pass-notification-services ITs fail

### ISSUE THREAD

**Issue by markpatton** [eclipse-pass/main#248]
Running ITs with:
```
mvn verify
```

they fail with exceptions like: 
```
testEmptyWhitelist(org.dataconservancy.pass.notification.dispatch.impl.email.EmailDispatchImplIT)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.RuntimeException: javax.mail.MessagingException: Certificates do not conform to algorithm constraints;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: Certificates do not conform to algorithm constraints
        at sun.security.provider.certpath.AlgorithmChecker.check(AlgorithmChecker.java:237)
        at sun.security.ssl.AbstractTrustManagerWrapper.checkAlgorithmConstraints(SSLContextImpl.java:1423)
        at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1352)
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1296)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:626)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:400)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:134)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:131)
        at com.sun.mail.imap.IMAPStore.newIMAPProtocol(IMAPStore.java:763)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:698)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at org.dataconservancy.pass.notification.SimpleImapClientFactory.getObject(SimpleImapClientFactory.java:81)
        at org.dataconservancy.pass.notification.dispatch.impl.email.EmailDispatchImplIT.setUp(EmailDispatchImplIT.java:126)
```

**Comment by markpatton** [comment]
This has been fixed by moving to a mailserver with newer certificates. The release should have the changes.
