### ISSUE TITLE
[Nihms Loader] Error processing publication

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#681]
From data run in stage:

```


INFO 19:55:23.668 (NihmsCsvProcessor) NIHMS record pmid=34856571 is being processed
--
WARN 19:55:24.101 (ResponseProcessCookies) Invalid cookie header: "Set-Cookie: ncbi_sid=52B548482D216E25_98A1SID; domain=.nih.gov; path=/; expires=Sat, 10 Aug 2024 19:55:23 GMT". Invalid 'expires' attribute: Sat, 10 Aug 2024 19:55:23 GMT
INFO 19:55:24.183 (NihmsPublicationToSubmission) No existing publication found for PMID "34856571", initiating new Publication record
INFO 19:55:24.183 (NihmsPublicationToSubmission) NIHMS RepositoryCopy record needed for PMID "34856571", initiating new RepositoryCopy record
WARN 19:55:24.183 (NihmsTransformLoadService) Update failed for PMID %s due to database conflict, attempting retry # %d
WARN 19:55:24.597 (ResponseProcessCookies) Invalid cookie header: "Set-Cookie: ncbi_sid=0B7976E8E44F44B3_EA51SID; domain=.nih.gov; path=/; expires=Sat, 10 Aug 2024 19:55:24 GMT". Invalid 'expires' attribute: Sat, 10 Aug 2024 19:55:24 GMT
INFO 19:55:24.679 (NihmsPublicationToSubmission) No existing publication found for PMID "34856571", initiating new Publication record
INFO 19:55:24.679 (NihmsPublicationToSubmission) NIHMS RepositoryCopy record needed for PMID "34856571", initiating new RepositoryCopy record
WARN 19:55:24.679 (NihmsTransformLoadService) Update failed for PMID %s due to database conflict, attempting retry # %d
WARN 19:55:25.085 (ResponseProcessCookies) Invalid cookie header: "Set-Cookie: ncbi_sid=D1DA67CB8D2F1FFC_6B1ESID; domain=.nih.gov; path=/; expires=Sat, 10 Aug 2024 19:55:24 GMT". Invalid 'expires' attribute: Sat, 10 Aug 2024 19:55:24 GMT
INFO 19:55:25.167 (NihmsPublicationToSubmission) No existing publication found for PMID "34856571", initiating new Publication record
INFO 19:55:25.167 (NihmsPublicationToSubmission) NIHMS RepositoryCopy record needed for PMID "34856571", initiating new RepositoryCopy record
ERROR 19:55:25.167 (NihmsCsvProcessor) A problem occurred while processing csv row 247 with pmid 34856571. The record was not imported successfully.
java.lang.RuntimeException: Update could not be applied for PMID 34856571 after 3 attempts
at org.eclipse.pass.loader.nihms.NihmsTransformLoadService.transformAndLoadNihmsPub(NihmsTransformLoadService.java:169)
at org.eclipse.pass.loader.nihms.NihmsTransformLoadService.lambda$transformAndLoadFiles$0(NihmsTransformLoadService.java:102)
at org.eclipse.pass.loader.nihms.NihmsCsvProcessor.consumeRow(NihmsCsvProcessor.java:167)
at org.eclipse.pass.loader.nihms.NihmsCsvProcessor.lambda$processCsv$0(NihmsCsvProcessor.java:133)
at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
at org.eclipse.pass.loader.nihms.NihmsCsvProcessor.processCsv(NihmsCsvProcessor.java:133)
at org.eclipse.pass.loader.nihms.NihmsTransformLoadService.transformAndLoadFiles(NihmsTransformLoadService.java:113)
at org.eclipse.pass.loader.nihms.NihmsTransformLoadApp.run(NihmsTransformLoadApp.java:106)
at org.eclipse.pass.loader.nihms.NihmsTransformLoadCLI.main(NihmsTransformLoadCLI.java:102)
Caused by: java.lang.IllegalArgumentException: publicationId cannot be empty
at org.eclipse.pass.client.nihms.NihmsPassClientService.readPublication(NihmsPassClientService.java:473)
at org.eclipse.pass.loader.nihms.NihmsPublicationToSubmission.initiateNewRepositoryCopy(NihmsPublicationToSubmission.java:283)
at org.eclipse.pass.loader.nihms.NihmsPublicationToSubmission.retrieveOrCreateRepositoryCopy(NihmsPublicationToSubmission.java:246)
at org.eclipse.pass.loader.nihms.NihmsPublicationToSubmission.transform(NihmsPublicationToSubmission.java:147)
at org.eclipse.pass.loader.nihms.NihmsTransformLoadService.transformAndLoadNihmsPub(NihmsTransformLoadService.java:153)
... 8 common frames omitted


```

**Comment by rpoet-jh** [comment]
AWS batch job in stage:

https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fbatch$252Fjob/log-events/stage-pass-data-loaders-nihms-job-def$252Fdefault$252F7d9692cb26354ecea5c513ea1ee7f568
