### ISSUE TITLE
Error when trying to cancel something at Review step

### ISSUE THREAD

**Issue by dkriethof** [eclipse-pass/main#790]
Hitting Cancel at the Review step does give the user an appropriate popup asking them to Discard Draft.
But clicking on "Abort" in Discard draft  popup, you get the attached error message.

![Image](https://github.com/eclipse-pass/main/assets/135133952/8d9fcfac-a0c1-44cf-b163-598487c6a584)

**Comment by rpoet-jh** [comment]
Error in console is:

```
Error occurred:

- While rendering:
  -top-level
    application
      submissions
        submissions.new
          submissions.new.review
            workflow-wrapper
              workflow-review


execute @ runtime.js:5208
...
actionHandler @ event_dispatcher.js:295
handleEvent._eventHandlers.<computed> @ event_dispatcher.js:318
error-handler.js:19 Handling error: "Assertion Failed: Cannot call filter before content is assigned."
error-handler.js:24 Error: Assertion Failed: Cannot call filter before content is assigned.
    at Object.assert (index.js:181:1)
    at PromiseManyArray.proxiedMethod [as filter] (-private.js:1686:1)
    at get weblinkRepos [as weblinkRepos] (index.js:315:1)
    at getPossibleMandatoryProxyValue (index.js:1979:1)
    at _getProp (index.js:2010:1)
    at _getPath (index.js:2048:1)
    at get (index.js:1996:1)
    at get mustVisitWeblink [as mustVisitWeblink] (index.js:320:1)
    at getPossibleMandatoryProxyValue (index.js:1979:1)
    at _getProp (index.js:2010:1)
