### ISSUE TITLE
Investigate Failed Record Imports for Nihms-loader in Pass Staging

### ISSUE THREAD

**Issue by tsande16** [eclipse-pass/main#798]
Small amount of records failed (166 out of 9,730) during the import of the nihms-loader AWS batch job. Will need to investigate to see why these failed to import, for example:

**CloudWatch Logs Insights**    
region: us-east-1    
log-group-names: /aws/batch/job    
start-time: 2023-10-24T14:59:00.000Z    
end-time: 2023-10-25T03:00:00.000Z    
query-string:
  ```
  fields @timestamp, @message, @logStream, @log
| filter @logStream = 'stage-pass-data-loaders-nihms-job-def/default/49ec184838f847138557212f6d6be823'
| filter @message like /A problem occurred while processing csv row/
| sort @timestamp desc
  ```
---
| @timestamp | @message | @logStream | @log |
| --- | --- | --- | --- |
| 2023-10-24 18:13:41.963 | ERROR 18:13:41.963 (NihmsCsvProcessor) A problem occurred while processing csv row 8458 with pmid 37789865. The record was not imported successfully. | stage-pass-data-loaders-nihms-job-def/default/49ec184838f847138557212f6d6be823 | 109693842411:/aws/batch/job |
| 2023-10-24 18:12:31.665 | ERROR 18:12:31.665 (NihmsCsvProcessor) A problem occurred while processing csv row 8411 with pmid 37777527. The record was not imported successfully. | stage-pass-data-loaders-nihms-job-def/default/49ec184838f847138557212f6d6be823 | 109693842411:/aws/batch/job |
| 2023-10-24 18:07:05.363 | ERROR 18:07:05.362 (NihmsCsvProcessor) A problem occurred while processing csv row 8140 with pmid 37691970. The record was not imported successfully. | stage-pass-data-loaders-nihms-job-def/default/49ec184838f847138557212f6d6be823 | 109693842411:/aws/batch/job |
| 2023-10-24 18:06:42.353 | ERROR 18:06:42.353 (NihmsCsvProcessor) A problem occurred while processing csv row 8124 with pmid 37681576. The record was not imported successfully. | stage-pass-data-loaders-nihms-job-def/default/49ec184838f847138557212f6d6be823 | 109693842411:/aws/batch/job |
| 2023-10-24 18:04:16.243 | ERROR 18:04:16.243 (NihmsCsvProcessor) A problem occurred while processing csv row 7999 with pmid 37648373. The record was not imported successfully. | stage-pass-data-loaders-nihms-job-def/default/49ec184838f847138557212f6d6be823 | 109693842411:/aws/batch/job |
| 2023-10-24 18:01:18.313 | ERROR 18:01:18.313 (NihmsCsvProcessor) A problem occurred while processing csv row 7836 with pmid 37587153. The record was not imported successfully. | stage-pass-data-loaders-nihms-job-def/default/49ec184838f847138557212f6d6be823 | 109693842411:/aws/batch/job |
---

**Comment by tsande16** [comment]
There were 164 records that have no matching award number, it comes down to 21 unique grants. 

Of these 21 grants, there were 2 grants that existed in `pass_grants` and 19 that were not in pass_grants . Checked this against  the front-end of Fibi and there grants were not in Fibi. My hypothesis from this is that PMC has award numbers that Fibi does not.

Of those two grants that did exist in pass_grants . I found the issue in the nihms-loader and will create a ticket this evening and put in a PR, this has now been fixed and merged by: https://github.com/eclipse-pass/main/issues/804

There remaining two errors are issues with `java.lang.NullPointerException: Cannot invoke "org.eclipse.pass.support.client.model.Repository.getId()" because "repo" is null`

From the cloud watch logs:

```
2023-10-24T11:22:14.617-04:00	ERROR 15:22:14.617 (NihmsCsvProcessor) A problem occurred while processing csv row 8 with pmid 33688771. The record was not imported successfully.
2023-10-24T11:22:14.617-04:00	java.lang.NullPointerException: Cannot invoke "org.eclipse.pass.support.client.model.Repository.getId()" because "repo" is null
2023-10-24T11:22:14.617-04:00	at org.eclipse.pass.support.client.SubmissionStatusCalculator.mapPostSubmissionRepositoryStatuses(SubmissionStatusCalculator.java:211)
2023-10-24T11:22:14.617-04:00	at org.eclipse.pass.support.client.SubmissionStatusCalculator.calculatePostSubmissionStatus(SubmissionStatusCalculator.java:77)

2023-10-24T11:22:16.081-04:00	ERROR 15:22:16.081 (NihmsCsvProcessor) A problem occurred while processing csv row 10 with pmid 33688771. The record was not imported successfully.
2023-10-24T11:22:16.081-04:00	java.lang.NullPointerException: Cannot invoke "org.eclipse.pass.support.client.model.Repository.getId()" because "repo" is null
2023-10-24T11:22:16.081-04:00	at org.eclipse.pass.support.client.SubmissionStatusCalculator.mapPostSubmissionRepositoryStatuses(SubmissionStatusCalculator.java:211)
2023-10-24T11:22:16.081-04:00	at org.eclipse.pass.support.client.SubmissionStatusCalculator.calculatePostSubmissionStatus(SubmissionStatusCalculator.java:77)
```

**Comment by tsande16** [comment]
The remaining two records with the issue `java.lang.NullPointerException: Cannot invoke "org.eclipse.pass.support.client.model.Repository.getId()" because "repo" is null` failed to import because of old lingering repo copies without a repoId in `pass_repository_copy`
