### ISSUE TITLE
Error in journal loader

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#858]
The journal loader failed on 12/19 with the following at the end of the log.

https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fbatch$252Fjob/log-events/pass-data-loaders-journal-job-def$252Fdefault$252F539e2371b2fb43c492acfa24531a7875$3Fstart$3D1702975500000$26end$3D1703048399000

```
2023-12-19T03:45:15.134-05:00 | INFO 08:45:15.134 (o.e.p.l.j.nih.LoaderEngine) Created 1 new journals
-- | --
  | 2023-12-19T03:45:15.134-05:00 | INFO 08:45:15.134 (o.e.p.l.j.nih.LoaderEngine) Updated 6 journals
  | 2023-12-19T03:45:15.134-05:00 | INFO 08:45:15.134 (o.e.p.l.j.nih.LoaderEngine) 7134 journals did not need updating
  | 2023-12-19T03:45:15.134-05:00 | INFO 08:45:15.134 (o.e.p.l.j.nih.LoaderEngine) Skipped 0 journals due to lack of ISSN and NLMTA
  | 2023-12-19T03:45:15.134-05:00 | INFO 08:45:15.134 (o.e.p.l.j.nih.LoaderEngine) Skipped 172 journals due to suspected duplication
  | 2023-12-19T03:45:15.134-05:00 | INFO 08:45:15.134 (o.e.p.l.j.nih.LoaderEngine) Could not load or update 0 journals due to an error
  | 2023-12-19T03:45:15.135-05:00 | Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 6, end -1, length 6
  | 2023-12-19T03:45:15.136-05:00 | at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
  | 2023-12-19T03:45:15.136-05:00 | at java.base/java.lang.String.substring(Unknown Source)
  | 2023-12-19T03:45:15.136-05:00 | at org.eclipse.pass.loader.journal.nih.MedlineReader.extractType(MedlineReader.java:107)
  | 2023-12-19T03:45:15.136-05:00 | at org.eclipse.pass.loader.journal.nih.MedlineReader.read(MedlineReader.java:84)
  | 2023-12-19T03:45:15.136-05:00 | at org.eclipse.pass.loader.journal.nih.MedlineReader$1.next(MedlineReader.java:64)
  | 2023-12-19T03:45:15.136-05:00 | at org.eclipse.pass.loader.journal.nih.MedlineReader$1.next(MedlineReader.java:50)
  | 2023-12-19T03:45:15.136-05:00 | at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
  | 2023-12-19T03:45:15.136-05:00 | at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
  | 2023-12-19T03:45:15.136-05:00 | at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
  | 2023-12-19T03:45:15.136-05:00 | at org.eclipse.pass.loader.journal.nih.LoaderEngine.load(LoaderEngine.java:58)
  | 2023-12-19T03:45:15.136-05:00 | at org.eclipse.pass.loader.journal.nih.Main.main(Main.java:79)
```

**Comment by tsande16** [comment]
Some initial debugging:

In the MedlineReader, if the String that is passed in at line 107 doesn't contain the parentheses  it will produced this error that is in the log: Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 6, end -1, length 6
