### ISSUE TITLE
Log harvest file reading errors

### ISSUE THREAD

**Issue by rpoet-jh** [eclipse-pass/main#954]
We ran into an issue where the nihms loader was failing trying to read the first harvest CSV file.  Looks like the nihms server was returning some HTML error response page instead of the CSV when we retrieved the harvest files.  

We should update NIHMS to log the contents of the file if the CSV fails on reading so we can see the exact content for troubleshooting.  We probably want to limit the logging to the first 500 lines or so of the content.

Here is the error from the logs:

```
INFO 09:44:59.748 (NihmsCsvProcessor) Starting to process file: /data/nihmsloader/data/noncompliant_nihmspubs_20240409094452.csv
ERROR 09:44:59.760 (NihmsCsvProcessor) Expected header "PMID" but was "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">"
java.lang.RuntimeException: A problem occurred while processing the csv with path /data/nihmsloader/data/noncompliant_nihmspubs_20240409094452.csv
	at org.eclipse.pass.loader.nihms.NihmsCsvProcessor.processCsv(NihmsCsvProcessor.java:137)
	at org.eclipse.pass.loader.nihms.NihmsTransformLoadService.transformAndLoadFiles(NihmsTransformLoadService.java:95)
	at org.eclipse.pass.loader.nihms.NihmsTransformLoadCLIRunner.run(NihmsTransformLoadCLIRunner.java:97)

**Comment by rpoet-jh** [comment]
@tsande16 not sure, but i don't think it is related to authentication because it started working after a second restart.  But this is why I opened the ticket, so we can what is in the harvest file (the HTML response) when this type of error happens.
